@baseUrl = http://localhost:3001
@jwtToken = {{authLogin.response.body.accessToken}}

@postUuid = {{createPostOwned.response.body.id}}
@postSlug = {{createPostOwned.response.body.slug}}
@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseUrl}}{{imagePath}}

@userNameForTesting = Tania
@userEmailForTesting = tania@email.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = 123456

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

# USER ########################################################################

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "{{userNameForTesting}}",
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "{{userNameForTesting}} Updated",
  "email": "{{userEmailForTesting}}"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "{{userPasswordForTesting}}",
  "newPassword": "{{userNewPasswordForTesting}}"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Delete one user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

# POST ########################################################################

### Create owned post
# @name createPostOwned
POST {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "Post Title",
  "excerpt": "Post Excerpt",
  "content": "Content",
  "coverImageUrl": "http://localhost"
}

### Read all public posts
# @name readAllPostPublic
GET {{baseUrl}}/post/

### Read one public post
# @name readOnePostPublic
GET {{baseUrl}}/post/{{postSlug}}

### Read all owned posts
# @name readAllPostOwned
GET {{baseUrl}}/post/me
Authorization: Bearer {{jwtToken}}

### Read one owned post
# @name readOnePostOwned
GET {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{jwtToken}}

### Update one owned post
# @name updateOnePostOwned
PATCH {{baseUrl}}/post/me/{{postUuid}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "PUBLISHED Post Title",
  "excerpt": "NEW - Excerpt",
  "content": "NEW - Content",
  "published": true
}

### Delete one owned post
# @name deleteOnePostOwned
DELETE {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{jwtToken}}

# UPLOAD ######################################################################

### Upload Image
# @name uploadImage
POST {{baseUrl}}/upload
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ../dev/images/image.png
------BryenFormBoundary--

### Read Image
# @name readImage
GET {{imageUrl}}

###############################################################################
