@baseUrl = http://localhost:3000

GET {{baseUrl}}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"belele@gmail.com",
    "pasword":"belele"
}
###